# Generated by Django 3.1.6 on 2021-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210217_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
